print("1. True = "  + str(True and True))
print("2. False = " + str(False and True))
print("3. False = " + str(1 == 1 and 2 == 1))
print("4. True = "  + str("test" == "test"))
print("5. True = "  + str(1 == 1 or 2 != 1))
print("6. True = "  + str(True and 1 == 1))
print("7. False = " + str(False and 0 != 0))
print("8. True = "  + str(True or 1 == 1))
print("9. False = "  + str("test" == "testing"))
print("10. False = "  + str(1 != 0 and 2 == 1))
print("11. True = "  + str("test" != "testing"))
print("12. False = "  + str("test" == 1))
print("13. True = "  + str(not (True and False)))
print("14. False = "  + str(not (1 == 1 and 0 != 1)))
print("15. False = "  + str(not (10 == 1 or 1000 == 1000)))
print("16. False = "  + str(not (1 != 10 or 3 == 4)))
print("17. True = "  + str(not ("testing" == "testing" and "Zed" == "Cool Guy")))
print("18. True = "  + str(1==1 and (not ("testing" == 1 or 1 == 0))))
print("19. False = "  + str("chunky" == "bacon" and (not (3 == 4 or 3 == 3))))
print("20. False = "  + str(3 == 3 and (not ("testing" == "testing" or "Python" == "Fun"))))
